import AllProvider from '@/providers/Auth-&-TRPCClient-Provider'
import type { Metadata } from 'next'
import "../assets/globals.css"

export const metadata: Metadata = {
	title: 'Clickk® | Home',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

	// const data = await serverClient.getData()
  	// const dataSet = await serverClient.setData("test-data trpc working in sever component")

	return (
		<html lang="en">
			<AllProvider>
				<body>
					{children}
				</body>
			</AllProvider>
		</html>
	)
}